matplotlib:
  axes:
    labelsize: 10
    titlesize: 16
  font:
    family: Cursive
    size: 4
  legend:
    fontsize: 16
    'on': true
  limits:
    xlim:
    - 4.0
    - 2.0
    xlim_enabled: true
    ylim:
    - 4.0
    - 4.0
    ylim_enabled: true
misc:
  normalized: true
